[project]
name = "homecheck"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "httpx>=0.28.1",
    "jinja2>=3.1.6",
    "pydantic<2.0",
    "webtypy>=0.1.7",
]

[dependency-groups]
dev = [
    "workers-py"
]
